
const UA: any = {
    'Salary': 'Зарплатня',
    'Mh': 'Мш',
    'L': 'Л',
    'January': "Січень",
    'February': "Лютий",
    'March': "Березень",
    'April': "Квітень",
    'May': "Травень",
    'June': "Червень",
    'July': "Липень",
    'August': "Серпень",
    'September': "Вересень",
    'October': "Жовтень",
    'November': "Листопад",
    'December': "Грудень",
    'Sunday': 'Неділя',
    'Monday': 'Понеділок',
    'Tuesday': 'Вівторок',
    'Wednesday': 'Середа',
    'Thursday': 'Четвер',
    'Friday': 'Пятниця',
    'Saturday': 'Субота',
    'Sun': 'Нед',
    'Mon': 'Пон',
    'Tue': 'Вів',
    'Wed': 'Сер',
    'Thu': 'Чет',
    'Fri': 'Пят',
    'Sat': 'Суб',
    'Edit Customer': 'Редагувати Клієнта',
    'Add Customer': 'Додати Клієнта',
    'Customer Name': 'Ім\'я Клієнта',
    'Price': 'Ціна',
    'Multishape': 'Мультішейп',
    'Laser': 'Лазер',
    'Is New': 'Новий',
    'Is Closed': 'Закрився',
    'Submit Form': 'Відправити Форму',
    'Please add customer': 'Будь ласка, додайте клієнта.',
    'Please, add customer for ${selectedDate}.${selectedMonth}.': 'Будь ласка, додайте клієнта на ${selectedDate}.${selectedMonth}.'
};

const EN: any = {
    'Salary': 'Salary',
    'Mh': 'Mh',
    'L': 'L',
    'January': "January",
    'February': "February",
    'March': "March",
    'April': "April",
    'May': "May",
    'June': "June",
    'July': "July",
    'August': "August",
    'September': "September",
    'October': "October",
    'November': "November",
    'December': "December",
    'Sunday': 'Sunday',
    'Monday': 'Monday',
    'Tuesday': 'Tuesday',
    'Wednesday': 'Wednesday',
    'Thursday': 'Thursday',
    'Friday': 'Friday',
    'Saturday': 'Saturday',
    'Sun': 'Sun',
    'Mon': 'Mon',
    'Tue': 'Tue',
    'Wed': 'Wed',
    'Thu': 'Thu',
    'Fri': 'Fri',
    'Sat': 'Sat',
    'Edit Customer': 'Edit Customer',
    'Add Customer': 'Add Customer',
    'Customer Name': 'Customer Name',
    'Price': 'Price',
    'Multishape': 'Multishape',
    'Laser': 'Laser',
    'Is New': 'Is New',
    'Is Closed': 'Is Closed',
    'Submit Form': 'Submit Form',
    'Please add customer': 'Please, add customer.',
    'Please, add customer for ${selectedDate}.${selectedMonth}.': 'Please, add customer for ${selectedDate}.${selectedMonth}.'
}

const localizationData: Record<'UA' | 'EN', any> = {
    UA, EN
}

export default localizationData;