
const EN = {
    'Salary': 'Salary',
    'Mh': 'Mh',
    'L': 'L',
    'January': "January",
    'February': "February",
    'March': "March",
    'April': "April",
    'May': "May",
    'June': "June",
    'July': "July",
    'August': "August",
    'September': "September",
    'October': "October",
    'November': "November",
    'December': "December",
    'Sunday': 'Sunday',
    'Monday': 'Monday',
    'Tuesday': 'Tuesday',
    'Wednesday': 'Wednesday',
    'Thursday': 'Thursday',
    'Friday': 'Friday',
    'Saturday': 'Saturday',
    'Sun': 'Sun',
    'Mon': 'Mon',
    'Tue': 'Tue',
    'Wed': 'Wed',
    'Thu': 'Thu',
    'Fri': 'Fri',
    'Sat': 'Sat',
    'Edit Customer': 'Edit Customer',
    'Add Customer': 'Add Customer',
    'Customer Name': 'Customer Name',
    'Price': 'Price',
    'Multishape': 'Multishape',
    'Laser': 'Laser',
    'Is New': 'Is New',
    'Is Closed': 'Is Closed',
    'Submit Form': 'Submit Form',
    'Please add customer': 'Please, add customer.',
    'Please, add customer for ${selectedDate}.${selectedMonth}.': 'Please, add customer for ${selectedDate}.${selectedMonth}.',
    'Is Transferred': 'Is Transferred',
    'Salary for Laser': 'Salary for Laser',
    'Salary for Multishape': 'Salary for Multishape',
    'Newcomers': 'Newcomers',
    'Closed Newcomers': 'Closed Newcomers',
    'Transferred customers': 'Transferred customers',
    'Salary for Transfers': 'Salary for Transfers',
    'Cream Price': 'Cream Price',
    'Creams sold': 'Creams sold',
    'Salary for Cream': 'Salary for Cream',
    'Nw': 'Nw',
    'Cl': 'Cl',
    'Cr': 'Cr',
    'Tr': 'Tr',
    'Are you sure that you want to clear selected month?': 'Are you sure that you want to clear selected month?',
    'Yes': 'Yes',
    'No': 'No',
}

const UA = {
    'Salary': 'Зарплатня',
    'Mh': 'Мш',
    'L': 'Л',
    'January': "Січень",
    'February': "Лютий",
    'March': "Березень",
    'April': "Квітень",
    'May': "Травень",
    'June': "Червень",
    'July': "Липень",
    'August': "Серпень",
    'September': "Вересень",
    'October': "Жовтень",
    'November': "Листопад",
    'December': "Грудень",
    'Sunday': 'Неділя',
    'Monday': 'Понеділок',
    'Tuesday': 'Вівторок',
    'Wednesday': 'Середа',
    'Thursday': 'Четвер',
    'Friday': 'Пятниця',
    'Saturday': 'Субота',
    'Sun': 'Нед',
    'Mon': 'Пон',
    'Tue': 'Вів',
    'Wed': 'Сер',
    'Thu': 'Чет',
    'Fri': 'Пят',
    'Sat': 'Суб',
    'Edit Customer': 'Редагувати Клієнта',
    'Add Customer': 'Додати Клієнта',
    'Customer Name': 'Ім\'я Клієнта',
    'Price': 'Ціна',
    'Multishape': 'Мультішейп',
    'Laser': 'Лазер',
    'Is New': 'Новий',
    'Is Closed': 'Закрився',
    'Submit Form': 'Відправити Форму',
    'Please add customer': 'Будь ласка, додайте клієнта.',
    'Please, add customer for ${selectedDate}.${selectedMonth}.': 'Будь ласка, додайте клієнта на ${selectedDate}.${selectedMonth}.',
    'Is Transferred': 'Переведена',
    'Salary for Laser': 'Зарплатня за Лазер',
    'Salary for Multishape': 'Зарплатня за Мультішейп',
    'Newcomers': 'Новенькі',
    'Closed Newcomers': 'Закриті Новенькі',
    'Transferred customers': 'Кількість Переведених',
    'Salary for Transfers': 'Зарплатня за Переведених',
    'Cream Price': 'Ціна за крем',
    'Creams sold': 'Продано крему',
    'Salary for Cream': 'Зарплатня за крем',
    'Nw': 'Н',
    'Cl': 'Зк',
    'Cr': 'Кр',
    'Tr': 'Пе',
    'Are you sure that you want to clear selected month?': 'Ви впевнені, що хочете очистити вибраний місяць?',
    'Yes': 'Так',
    'No': 'Ні',
};

export type localizationType = typeof EN;

const localizationData: Record<'UA' | 'EN', localizationType> = {
    UA, EN
}

export default localizationData;
